### ISSUE TITLE
list issues [command: hub issue]

### ISSUE THREAD

**Issue by bandresen** [vermiculus/magithub#13]
It would be cool if you could get a list of issues in magithub

it's available in hub version 2.2.5 (beta though)

**Comment by vermiculus** [comment]
Already working on it :smile:

I had some weird version issues with my own copy of hub that kept me from doing it this past weekend, but you should look for it by next Monday. (Somehow I had the gem installed *and* the copy installed with brew? Since different tools were using different paths, I was getting different results.)

**Comment by vermiculus** [comment]
:shipit:
