### ISSUE TITLE
Fetch branches of pull requests from magit-status

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#14]
[Discussed on reddit][1]; this would be nice to have and is an obvious enhancement.

[1]: https://www.reddit.com/r/emacs/comments/537w8u/magithub_magit_interfaces_for_github/d7u8g66

**Comment by vermiculus** [comment]
This can be done with `hub checkout`.

**Comment by blaenk** [comment]
I'd love the ability to perform some key bind on a PR and have it somehow checkout those changes locally so I can test them and optionally merge and push them with magit.

Note that this only concerns fetching changes from a PR, not merging. Currently #42 uses `hub am` which merges the PR changes into the current branch. What I'd like is to end up with a branch that represents the changes so I can work with it in isolation.

I think it would be useful to have two different strategies for checking out PR changes locally:

1. Add the remote of the PR source repo (if it's not the current and it's not already added), which prompts the user for the remote name (by default it's the name of the user that filed the PR), then simply checks out (using magit?) the source branch of the PR.

    This is how I typically do things manually, as it allows me to easily check out new PRs from repeat contributors.

2. The more quick-and-dirty remote ref feature github has, outlined [here](https://help.github.com/articles/checking-out-pull-requests-locally/), which essentially results in an ephemeral branch containing the PR changes. The hub command which magithub currently relies on has some sugar for this, though if you look at the page linked above it's not much more work to do it manually (git fetch followed by a git checkout):

    Manually:

    >     $ git fetch origin pull/<pull-request-ID>/head:<local-branch-name>
    >     $ git checkout <local-branch-name>

    Using hub:

    >     # check out a pull request for review
    >     $ git checkout https://github.com/github/hub/pull/134
    >     → (creates a new branch with the contents of the pull request)

**Comment by vermiculus** [comment]
What's wrong with the current approach of `hub checkout`? The only possible deficiency I see is mentioned in (1):

> it allows me to easily check out new PRs from repeat contributors.

which I'd imagine is made moot by creating a keybind on (2).

**Comment by blaenk** [comment]
I was unclear at first as to what you meant, if perhaps you were saying I should just use `$ hub checkout` in the shell. That caused me to wonder if this functionality is already built in, and it seems like it is!

I had missed it at first because what I'm proposing is to be able to do this through the magithub UI, so I could press a key on one of the listed pull requests and it'll check that out. Instead what seems to be implemented is an interactive function that is given a completing read list of the existing PRs.

That seems pretty cool! However, I think indeed it would be a great feature to be able to create a keybind on it. Perhaps something like magit's git-ignore keybind, where it'll still do a completing read but it'll show the file at-point as the first option. So this would mean that if I have the point on a PR, it'll show that PR at the beginning, but otherwise show all of the PRs.

Yeah I suppose if this functionality were that simple (via a keybind) it might erase the benefits of having separate remotes for each PR, plus it'll mean less clutter. I'll have to try it and see.

**Comment by vermiculus** [comment]
Hm, I thought I'd done so (the completing functionality you describe is already present in `magithub-pull-request--completing-read`). Looks like I forgot to bind it!

**Comment by vermiculus** [comment]
Do you have any opinions on a good default keybinding? I'm swinging between `b` and `C` (both only active when point is on a PR).

**Comment by blaenk** [comment]
I think `b` would be nicer than having to do shift-C, and we can associate it with "branch." Either one works though I suppose.

I also remembered [this comment](https://github.com/vermiculus/magithub/pull/42#issuecomment-253773924) and I think it would be amazing if it were possible to naturally use existing magit "vocabulary" which IMO would be much more fluent and logical than first having to go into the magithub prefix `H` then do `b` which only works when the point is on a PR.

If so then I guess something like `b p` for checkout pull request. The `b b` key seems to just be a "do what I mean" (dwim) feature (haven't tested but perhaps if point is on a revision it would check out that revision) and I think it would be amazing if there were a way to "teach" magit about another kind of thing (PR) that it can checkout with it, either through some kind of magit API or by advising functions, but perhaps that would be going too far.

**Comment by vermiculus** [comment]
I've added `b p` as a feature injection 😄

…without testing it first ☹️ `b p` is taken; so is `b C`. Gonna go with `b P` unless there are objections or other suggestions.

I'm trying to inject it right into `b b`, but the advice is slow-going.

**Comment by blaenk** [comment]
`b P` is fine, the fact that the keybind will exist at all is already extremely helpful. Thank you very much! I also look forward to hearing how it goes with `b b`.

**Comment by vermiculus** [comment]
@blaenk Let me know if you have any issue with the above 👍

**Comment by blaenk** [comment]
Will do, thank you very much!
