### ISSUE TITLE
not clear how to accept selected labels when creating new issue

### ISSUE THREAD

**Issue by brettatoms** [vermiculus/magithub#168]
When creating a new issue with `magithub-issue-new` it's not clear how to accept/confirm the labels that you've selected and progress to the next screen.  First it asks me for the issue title and then I'm presented with a list of labels.  Hitting enter on the labels removes them from the list which I assume adds them to the new issue but I'm not sure what to do to accept the labels that I added and progress to the next screen.

**Comment by vermiculus** [comment]
What completion engine are you using? You basically want a value of null to stop; this is the same behavior as at least one other place in REL emacs.

**Comment by brettatoms** [comment]
I use company mode for code completions, etc and ivy for minibuffer completions.  My setup is more or less stock spacemacs otherwise.

**Comment by vermiculus** [comment]
"Stock spacemacs" is almost an oxymoron to me 😉 For ivy (on not-spacemacs), you want to use `C-M-j`:

```
ivy-immediate-done is an interactive compiled Lisp function …

(ivy-immediate-done)

Exit the minibuffer with current input instead of current candidate.
```

In the past (sx.el comes to mind), the approach was to use a special 'DONE' value, but I don't think this would be a good approach here since something like 'DONE' could easily be a label itself.

Since this is implementation-dependent (and outside magithub's control), I'm gonna close this issue, but I'd be happy to help further if I can.

**Comment by brettatoms** [comment]
@vermiculus Thanks for help, I really appreciate it...and thanks for magithub.
