### ISSUE TITLE
don't retrive everytime

### ISSUE THREAD

**Issue by stardiviner** [vermiculus/magithub#22]
The CI status should not run if repository does not have CI. To speedup the Magit status buffer show up.
Maybe `defcustom` an option which let user choose whether enable this feature?
It can be put in popup action menu, manually retrive CI status and pull requests and issues.
Too frequently retriving CI status will cause magit-status very slow.

**Comment by vermiculus** [comment]
It's probably more appropriate to use a git repo property (like we do to store the URL), but the workflow needs to be thought out a little. My main concern is keeping this 'on by default' for repositories that *do* have CI.

Here's one possible workflow:
1. User clones repo
1. On magit-status, if ci-status is `'no-status`, ask the user (`y-or-n-p`) if they would like to use CI
  * if Yes, ask for URL and set the property `magithub.ci.url` to a URL retrieved from the user.
  * if No, set the property `magithub.ci.no_ci`.

These properties could be set by the user manually with a new CI management popup in the Magithub dispatcher. Since these are just normal git properties, there might be a framework for this inside Magit -- I'll have to investigate. Of course, if the user *never* wants to use CI, they could set this property globally.

I'll see what I can do, but this *actually* isn't probably going to get done before Monday evening -- I'll be out of town for the weekend and I've got to clean up the apartment tonight for a friend to take care of my cat :smile_cat:

**Comment by stardiviner** [comment]
I see. It's fine. I think your workflow is good. That can meet my desire. Thanks.

**Comment by vermiculus** [comment]
Does the current behavior meet your goals?

Right now, we're only refreshing CI status once a minute if and only if the last commit's status wasn't `'success`. Manual refreshing is done by using `g` (or whatever `magit-refresh` is bound to) on the CI status header.

**Comment by stardiviner** [comment]
This is better now. Thanks for your working.
