### ISSUE TITLE
Pull request created against the wrong fork

### ISSUE THREAD

**Issue by mithrandi** [vermiculus/magithub#311]
When I create a pull request via `H` `p`, it tells me that I will merge `mithrandi:my-branch` into `fusionapp/fusion:master` (this is the name of the upstream repo) which is what I want to do, but in fact the PR is actually created against `mithrandi/fusion:master` which is not what I want. Also, there is no default for "base branch", I have to enter `master` manually.

`(magit-get-upstream-branch (magit-get-current-branch))`
returns
`#("upstream/master" 0 15 (face magit-branch-remote))`

**Comment by jonathanj** [comment]
Seems like the issue is that the `repo` parameter to `magithub-pull-request-new` is not passed along to `magithub-pull-request-submit`, meaning that within the submit function `magithub-repo` is invoked without an explicit repo and so the pull request is created against the forked repo and not the intended destination repo.
