### ISSUE TITLE
magihhub.contextRemote doesn't cycle through remote names anymore

### ISSUE THREAD

**Issue by philsf** [vermiculus/magithub#407]
Hello, thanks so much for this package.

A few weeks ago I noticed I can't choose the remote name for a repo as I was used to. When I check the config, there is no list to cycle through (screenshot below). I can revert to using "origin" as the remote name, but this worked well for years. I don't remember when exactly it stopped working but for reference his seemed to happen a few days *before* the release of magit 3.1.0).

![Captura de tela de 2021-07-07 18-38-31](https://user-images.githubusercontent.com/5522672/124832458-173bb280-df53-11eb-9bcc-7455db724594.png)

Currently using magithub version 20190512.2316 (from melpa) and magit version 3.1.1 (from melpa-stable), on emacs 27.1 (Linux). Let me know if you need versions for other packages.

**Comment by vermiculus** [comment]
What's interesting to me is that there seems to be an 'empty' option on that line (indicated by the lone pipe character). I'm not sure what could be the issue there; as far as this package is concerned (as far as I can recall), these are just git-config settings and you should be able to set them to strings. So, worst case, you can just `git config magithub.contextremote YOUR_REMOTE_HERE` and that should work just as well.

That said, I haven't maintained this project in a long time -- you're probably better off switching to Forge 😄 I don't suspect I'll be able to devote resources to this project in any reasonable amount of time. (That's code for: if I need a new feature added to my magit workflows, I'm more likely to add it to Forge since my work doesn't use github -- or any host, for that matter).

I'm going to leave this issue open in case the `git config` stuff doesn't work for you.

**Comment by philsf** [comment]
[snip]


> Another interesting fact is that your transient popup is called `test`. Did you make a custom one? (Or did I leave that in there?)

I noticed this too. I have absolutely no idea if it's related to my init config, or if it's the package. I'm not 
 
> That said, I haven't maintained this project in a long time -- you're probably better off switching to Forge  I don't suspect I'll 

Ahhh, I haven't read about forge until you said this lol. When I read "migrating to forge" I assumed those would be improvements on this package using a different infrastructure (like the magit-popup -> transient case).

I migrated my workflow to forge and uninstalled magithub for now. Ironically now I have a hard incentive to use `origin` instead of a custom name, because it requires me to manually set `git config forge.remote` for each repo. I liked how easy magithub was, but now that forge is up and running, all's good for me.

> I'm going to leave this issue open in case the git config stuff doesn't work for you.

No need anymore, thanks my friend.
