### ISSUE TITLE
No pull requests listed with hub 2.3.0-pre8

### ISSUE THREAD

**Issue by tarsius** [vermiculus/magithub#44]
For me "Issues and Pull Requests" does not list any of the latter.  I'm using hub 2.3.0-pre8, haven't tried with 2.2 yet (but wanted to use magithub for the first time to create an issue now ;-).  `hub issue` also doesn't list any pull requests.

**Comment by vermiculus** [comment]
Hmm… you're right. It looks like 2.3 just doesn't return pull requests for `hub issue` like it used to 😠 

I'll see what I can do to mitigate this. Related #43

**Comment by tarsius** [comment]
I went back to 2.2.9 and that works.

**Comment by mislav** [comment]
@vermiculus To reflect our web UI, I decided that `hub issue` should only list issues and that there should be a separate command for listing pull requests. This command will come soon and will definitely be included in the stable release.

How is magithub using `hub issue`? Will it be inconvenient that there are separate commands for listing issues/PRs?

**Comment by vermiculus** [comment]
Magithub basically just parses the output of various `hub` commands as best it can and inserts them into the `magit-status` buffer.

Specifically for `hub issue`, in 2.2.x I was able to parse each line of output with a simple regex (`<num>]<title>(<url>)`) and detect pull requests by the URL. These issues were then processed into objects and inserted into the buffer as actionable sections.

In 2.3.x (or 3.x, which makes more sense to me), I'm able to use the new `--format` option (which *is* awesome, by the way!) to make it more foolproof (yet overall a little more complicated) to parse. They're eventually parsed into the same objects and inserted into the buffer the same way.

The only true inconvenience I can foresee (that can't be *really* solved with any amount of code on my end) is the extra network lag for pulling issues *and then* pull requests – I imagine it would take the same amount of time for both commands (since right now `hub` just filters them out or information already received). This would be mitigated (for all users of `hub`) by the caching functionality described in github/hub#1232, but I know from personal experience that caching is, in general, a hard problem.

**Comment by mislav** [comment]
> I'm able to use the new `--format` option (which _is_ awesome, by the way!) to make it more foolproof (yet overall a little more complicated) to parse.

That's exactly why the `--format` option was introduced.

> the extra network lag for pulling issues _and then_ pull requests

Do you always need to fetch both lists at the same time? Maybe `hub issue` could have a flag to *not* filter out PRs.

**Comment by vermiculus** [comment]
> Do you always need to fetch both lists at the same time?

The answer is… probably. I don't think Magithub will ever reach a level of sophistication where those individual sections can all be turned on/off (though this is happening for CI status, so maybe I'm already wrong). The fewer network calls I have to make, the better: emacs is 'by default' a single-threaded application (see #37) so I don't want to lock folks up too bad.
